In [2]:
!pip install scikit-learn

zsh:1: command not found: pip

In [3]:
from sklearn.linear_model import LogisticRegression

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [8]:
df = sns.load_dataset("titanic")

print("Shape:", df.shape)
df.head()

Shape: (891, 15)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [10]:
df = sns.load_dataset("titanic") # Reload the original dataset

print(df.columns.tolist())

#Keep only the columns we actually want to use as features + the target.

df = df[["survived", "pclass", "sex", "age", "sibsp", "parch", "fare", "embarked"]].copy()

df.head()

['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

   survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [11]:
print(df.isnull().sum())

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [12]:
df["age"] = df["age"].fillna(df["age"].median())

#"embarked" (port) has just 2 missing values -> fill with the MODE #(the most common port) since it's categorical, not numeric.

df["embarked"]= df["embarked"].fillna (df["embarked"].mode()[0])

#Confirm nothing is missing anymore.

print(df.isnull().sum())

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
dtype: int64

In [13]:
df["age"] = df["age"].fillna(df["age"].median())

#"embarked" (port) has just 2 missing values -> fill with the MODE

#(the most common port) since it's categorical, not numeric.

df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

# Confirm nothing is missing anymore.

print(df.isnull().sum())

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
dtype: int64

In [14]:
df["family_size"] = df["sibsp"] + df["parch"] + 1 #+1 to count the passenger

#Encode "sex" as 0/1 (this is a simple manual encoding fine for a binary cati

df["sex"] = df["sex"].map({"male": 0, "female": 1})

#Encode "embarked" (3 possible ports) as 0/1/2.

df["embarked"]= df["embarked"].map({"S": 0, "C": 1, "Q": 2})

df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  family_size
0         0       3    0  22.0      1      0   7.2500         0            2
1         1       1    1  38.0      1      0  71.2833         1            2
2         1       3    1  26.0      0      0   7.9250         0            1
3         1       1    1  35.0      1      0  53.1000         0            2
4         0       3    0  35.0      0      0   8.0500         0            1

In [15]:
X = df[["pclass", "sex", "age", "fare", "family_size", "embarked"]]

y = df["survived"]

print("Features used:", X.columns.tolist())

print("Target: survived (e did not survive, 1 survived)")

Features used: ['pclass', 'sex', 'age', 'fare', 'family_size', 'embarked']
Target: survived (e did not survive, 1 survived)

In [16]:
RANDOM_STATE = 42
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=RANDOM_STATE )

print("Training rows:", X_train.shape[0])

print("Testing rows:", X_test.shape[0])

Training rows: 712
Testing rows: 179